Numpy
- convert A list,tuple,dict in to Numpy array
- How to generate array with in a range of values
    - arange
    - linspace
    - random.randint
- basic arthimetc operators on numpy array

In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# How to slicing 
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [9]:
# Fancy Indexing or Boolean Indexing
print(a[a>5])

[6 7 8 9]


In [11]:
a.shape

(10,)

In [12]:
a.ndim

1

In [13]:
a2 = np.random.randint(10,30,(3,3))
a2

array([[24, 22, 14],
       [25, 21, 15],
       [29, 11, 18]])

In [15]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [19]:
for i in a2:
    print(i)
    break

[24 22 14]


In [18]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()

24 22 14 
25 21 15 
29 11 18 


In [25]:
print(a2[0],type(a2[0]),a2[0].shape)

[24 22 14] <class 'numpy.ndarray'> (3,)


In [24]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[25 21 15]
 [29 11 18]] <class 'numpy.ndarray'> (2, 3)


In [28]:
# rows from 0  to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

15
15


In [47]:
print(a2[1:3])

[[25 21 15]
 [29 11 18]]


In [29]:
print(a2[1:3,0:2])

[[25 21]
 [29 11]]


In [30]:
print(a2)

[[24 22 14]
 [25 21 15]
 [29 11 18]]


In [32]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[27, 35, 84],
        [81, 50, 25],
        [50, 97, 85],
        [72, 23, 83],
        [68, 90, 93]],

       [[15, 60, 33],
        [86, 19, 26],
        [86, 38, 60],
        [83, 74, 39],
        [63, 53, 32]],

       [[36, 76, 82],
        [34, 16, 46],
        [77, 67, 95],
        [36, 84, 35],
        [76, 72, 84]],

       [[79, 49, 45],
        [79, 88, 86],
        [98, 50, 77],
        [90, 39, 96],
        [15, 10, 15]],

       [[70, 58, 32],
        [92, 10, 14],
        [26, 50, 97],
        [27, 85, 16],
        [38, 29, 52]]])

In [48]:
print(a3[:2]) # indices - 0,1

[[[27 35 84]
  [81 50 25]
  [50 97 85]
  [72 23 83]
  [68 90 93]]

 [[15 60 33]
  [86 19 26]
  [86 38 60]
  [83 74 39]
  [63 53 32]]]


In [34]:
print(a3[1::2])

[[[15 60 33]
  [86 19 26]
  [86 38 60]
  [83 74 39]
  [63 53 32]]

 [[79 49 45]
  [79 88 86]
  [98 50 77]
  [90 39 96]
  [15 10 15]]]


In [35]:
print(a3[1::2,2])

[[86 38 60]
 [98 50 77]]


In [36]:
print(a3[1::2,0:5:2])

[[[15 60 33]
  [86 38 60]
  [63 53 32]]

 [[79 49 45]
  [98 50 77]
  [15 10 15]]]


In [37]:
print(a3[1::2,0:5:2,2])

[[33 60 32]
 [45 77 15]]


In [39]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True, False, False],
        [ True, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [40]:
# Boolean Indexing
a3[a3==86]

array([86, 86, 86])

In [41]:
a3[a3>50]

array([84, 81, 97, 85, 72, 83, 68, 90, 93, 60, 86, 86, 60, 83, 74, 63, 53,
       76, 82, 77, 67, 95, 84, 76, 72, 84, 79, 79, 88, 86, 98, 77, 90, 96,
       70, 58, 92, 97, 85, 52])

In [44]:
a3[(a3>50) & (a3<70)] #or -- |

array([68, 60, 60, 63, 53, 67, 58, 52])

In [46]:
a3[(a3<50) | (a3>70)]

array([27, 35, 84, 81, 25, 97, 85, 72, 23, 83, 90, 93, 15, 33, 86, 19, 26,
       86, 38, 83, 74, 39, 32, 36, 76, 82, 34, 16, 46, 77, 95, 36, 84, 35,
       76, 72, 84, 79, 49, 45, 79, 88, 86, 98, 77, 90, 39, 96, 15, 10, 15,
       32, 92, 10, 14, 26, 97, 27, 85, 16, 38, 29])

In [50]:
L = list(range(100))
# 0,1,2,3--- L[:]
# 1,2,3,4.... L[1:]
# 1,3,5,7,9,11,13 #L[1::2]
# 1,13,45,74,23,67 # 

In [51]:
aL = np.array(L)
aL[[1,13,45,74,23,67]] 

array([ 1, 13, 45, 74, 23, 67])

In [52]:
aL[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [53]:
a2

array([[24, 22, 14],
       [25, 21, 15],
       [29, 11, 18]])

In [54]:
a2[[1,2],[0,1]] # (1,0)(2,1)

array([25, 11])

In [58]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])

[19 95]
19
95


In [ ]:
statistical Functions 

In [60]:
a = np.random.randint(20,30,5)
a

array([24, 25, 29, 27, 23])

In [62]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

25.6
25.6


In [63]:
# sorted a [23,24,25,27,29]
np.median(a)

25.0

In [66]:
print(np.quantile(a,0.25)) # Q1
print(np.quantile(a,0.5)) # Q2
print(np.quantile(a,0.75)) # Q3

24.0
25.0
27.0


In [ ]:
## Logorithemic and Exponential

In [88]:
import numpy as np
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [87]:
print(np.log2(2))
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [74]:
#np.log(0)
#np.log2(0)
# np.log10(0)

C:\Users\Krish\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until


-inf

In [75]:
np.log(0+1)

0.0

In [78]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0)) # np.log(1+0)

1.0986122886681098
0.0


In [79]:
np.exp(1)

2.718281828459045

In [80]:
np.exp(2)

7.38905609893065

In [81]:
print(np.exp2(4))#2**4

16.0


In [86]:
print(np.expm1(2))# np.exp(2)-1
print(np.exp(2)-1)

6.38905609893065
6.38905609893065
